#!/usr/sbin/nft -f

flush ruleset

table ip nat {
       chain postrouting {
              type nat hook postrouting priority srcnat; policy accept;
              ip saddr 10.0.0.0/8 oifname "enp0s3" masquerade
       }
}


table inet filter {
        chain input {
                type filter hook input priority filter; policy drop;
                ct state established,related accept
                ct state invalid drop
            
                iif "lo" accept
                ip saddr 10.0.2.2 iifname "enp0s3" tcp dport 22 accept
                ip saddr 10.0.0.0/8 icmp type echo-request accept
                ip saddr 10.0.30.10 iifname "enp0s9.30" tcp dport 22 accept
        }

	chain forward {
                type filter hook forward priority filter; policy drop;
                ct state established,related accept
                ct state invalid drop
                
                ip saddr 10.0.10.10 ip daddr 10.0.20.10 tcp dport 5432 accept
                ip saddr 10.0.30.10 ip daddr 10.0.20.10 tcp dport 5432 accept
                ip saddr 10.0.30.10 ip daddr 10.0.10.10 tcp dport 22 accept
                ip saddr 10.0.0.0/8 oifname "enp0s3" accept 
                ip saddr 10.0.30.10 ip daddr 10.0.20.10 tcp dport 22 accept
                ip saddr 10.0.30.10 ip daddr 10.0.10.10 tcp dport 80 accept
	}
	chain output {
		type filter hook output priority filter; policy accept
	}
}
